[build]
  command = "npm run build:sitemap"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Netlify Functions
[functions]
  directory = "netlify/functions"

# Submit Sitemap Plugin
[[plugins]]
package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
  baseUrl = "https://moxiethemes.com"
  sitemapPath = "/out/sitemap.xml"
  ignorePeriod = 0
  providers = [
    "google",
    "yandex"
  ]

# Headers for better caching
[[headers]]
  for = "/images/og-*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for OG images
[[redirects]]
  from = "/api/og-image"
  to = "/.netlify/functions/og-image"
  status = 200

[[redirects]]
  from = "/api/og-default"
  to = "/.netlify/functions/og-image"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/out/sitemap.xml"
  status = 200